[build]
builder = "nixpacks"
buildCommand = "bun run build"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["bun"]

[build.nixpacksPlan.phases.install]
dependsOn = ["setup"]
cmds = ["bun install"]

[deploy]
startCommand = "bun run start"
healthcheckPath = "/api/rates"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
